language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t augyu/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true augyu/docker-react-aws npm run test
