language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t augyu/docker-react-aws -f Dockerfile.dev .

script:
  - docker run -e CI=true augyu/docker-react-aws npm run test

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'docker-react-aws'
  env: 'Dockerreactaws-env'
  bucket_name: 'elasticbeanstalk-us-east-1-694032273284'
  bucket_path: 'docker-react-aws'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
